import { useEffect,useRef,useState,type ReactNode } from 'react';
import { AlertCircle,ArrowLeft,BarChart3,Check,CheckCircle2,ChevronRight,Clock3,ExternalLink,FileSpreadsheet,FileText,LogOut,MessageSquare,MoreHorizontal,RefreshCw,Search,Shield,Upload,Users,X } from 'lucide-react';
import { supabase } from './client';
import { loadDataset,loadProfile,rpc,saveSurvey } from './data';
import { classStudents,emptyDataset,renderMessage,responseFor,stats,validSurveyUrl,whatsappUrl,type ClassRow,type Dataset,type Form4Submission,type Profile,type Student,type Survey } from './domain';
import { brazilToday } from './management';
import { reconcileForm4 } from './matching';
import Dialog from './Dialog';
import ImportWorkflows,{type WorkflowKind,type WorkflowPayload} from './ImportWorkflows';
import AIAnalysis from './AIAnalysis';
type Page='overview'|'classes'|'imports'|'review'|'analysis'|'messages'|'access';
const errorText=(e:unknown)=>e instanceof Error?e.message:typeof e==='object'&&e&&'message' in e?String(e.message):'Não foi possível concluir.';
const date=(value?:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'America/Sao_Paulo'}).format(new Date(value.length===10?value+'T15:00:00Z':value)):'—';
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join('');
const urnLabel=(urn:string)=>urn.startsWith('SEM-')?'—':urn;
function Brand(){return <div className="brand-v2"><img src={`${import.meta.env.BASE_URL}arca.png`} alt="arca"/><div><strong>SIDP</strong><small>MERL · FASE V</small></div></div>;}
function Empty({children}:{children:ReactNode}){return <div className="empty"><Users size={27}/><p>{children}</p></div>;}
function Metric({label,value,icon,color='neutral'}:{label:string;value:number|string;icon:ReactNode;color?:string}){return <div className={`metric ${color}`}><div><span>{label}</span><span className="metric-icon">{icon}</span></div><strong>{value}</strong></div>;}
export default function App(){
  const [profile,setProfile]=useState<Profile|null>(null),[data,setData]=useState<Dataset>(emptyDataset()),[loading,setLoading]=useState(!!supabase);
  const [page,setPage]=useState<Page>('overview'),[classId,setClassId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const [workflow,setWorkflow]=useState<WorkflowKind|null>(null),[editing,setEditing]=useState<Student|null>(null);
  const [aiReview,setAIReview]=useState<{submissionId:string;studentId:string;classId:string}|null>(null);
  const version=useRef(0);const admin=profile?.role==='admin';const classroom=data.classes.find(c=>c.id===classId);const survey=data.surveys.find(s=>s.class_id===classId&&s.code==='F4');
  const refresh=async()=>{if(profile)setData(await loadDataset(profile.role==='admin'));};
  useEffect(()=>{if(!supabase)return;const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{const current=++version.current;if(!session){setProfile(null);setData(emptyDataset());setLoading(false);return;}setLoading(true);setError('');setTimeout(()=>{void (async()=>{try{const p=await loadProfile(session.user.id);const d=await loadDataset(p.role==='admin');if(current===version.current){setProfile(p);setData(d);}}catch(e){if(current===version.current)setError(errorText(e));}finally{if(current===version.current)setLoading(false);}})();},0);});return()=>subscription.unsubscribe();},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
  async function mutate(operation:()=>Promise<unknown>,notice:string){if(!admin)throw new Error('Acesso administrativo necessário.');setBusy(true);setError('');try{await operation();await refresh();setToast(notice);}catch(e){setError(errorText(e));throw e;}finally{setBusy(false);}}
  async function saveImport(kind:WorkflowKind,payload:WorkflowPayload,filename:string){await mutate(()=>rpc(kind==='management'?'import_management':kind==='attendance'?'import_attendance':'import_form4',kind==='management'?{p_rows:payload.rows,p_filename:filename}:kind==='attendance'?{p_class_id:payload.classId,p_rows:payload.rows,p_filename:filename}:{p_rows:payload.rows,p_source:payload.source,p_filename:filename}),'Dados importados.');}
  async function logout(){version.current++;setWorkflow(null);setEditing(null);setAIReview(null);setPage('overview');setClassId(null);setProfile(null);setData(emptyDataset());if(supabase){const {error}=await supabase.auth.signOut();if(error)setError(error.message);}}
  async function reload(){setBusy(true);try{await refresh();setToast('Atualizado.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  const reviews=data.submissions.filter(s=>s.state==='review').length;
  const nav=[{id:'overview',label:'Visão geral',icon:BarChart3},{id:'classes',label:'Turmas',icon:Users},...(admin?[{id:'imports',label:'Dados',icon:Upload},{id:'review',label:'Conferência',icon:AlertCircle},{id:'analysis',label:'Análise IA',icon:BarChart3},{id:'messages',label:'Mensagens',icon:MessageSquare},{id:'access',label:'Acessos',icon:Shield}]:[])];
  if(loading)return <div className="loading"><Brand/><RefreshCw size={24} className="spin"/></div>;
  if(!profile)return <Login error={error}/>;
  const totals=data.classes.reduce((acc,c)=>{const st=stats(data,c,data.surveys.find(s=>s.class_id===c.id&&s.code==='F4'));return {total:acc.total+st.total,answered:acc.answered+st.answered,pending:acc.pending+st.pending};},{total:0,answered:0,pending:0});
  return <div className="app-shell"><aside className="sidebar"><Brand/><nav className="minimal-nav" aria-label="Navegação">{nav.map(n=><button key={n.id} className={`nav-item ${page===n.id?'active':''}`} onClick={()=>{setPage(n.id as Page);setClassId(null);}}><n.icon size={19}/>{n.label}{n.id==='review'&&reviews>0&&<small>{reviews}</small>}</button>)}</nav><div className="sidebar-bottom"><div className="user"><span className="avatar">{initials(profile.full_name||profile.email)}</span><div><strong>{profile.full_name||profile.email}</strong><small>{admin?'Admin':'Implementadora'}</small></div><button className="icon-button" aria-label="Sair" onClick={()=>void logout()}><LogOut size={18}/></button></div></div></aside>
    <main className="main"><header className="topbar"><span>Form 4<ChevronRight size={14}/>{classroom?.code||nav.find(n=>n.id===page)?.label}</span><button className="icon-button" aria-label="Atualizar" disabled={busy} onClick={()=>void reload()}><RefreshCw size={17} className={busy?'spin':''}/></button></header><div className="content">
      {error&&<div className="alert error" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="Fechar aviso" onClick={()=>setError('')}><X size={16}/></button></div>}
      {(page==='overview'||page==='classes')&&!classroom&&<><div className="page-heading"><h1>{page==='overview'?'Form 4':'Turmas'}</h1>{admin&&<button className="button primary" onClick={()=>setWorkflow('management')}><Upload size={17}/>Quadro de gestão</button>}</div>{page==='overview'&&<div className="metrics"><Metric label="Participantes" value={totals.total} icon={<Users size={19}/>}/><Metric label="Responderam" value={totals.answered} icon={<CheckCircle2 size={19}/>} color="green"/><Metric label="Pendentes" value={totals.pending} icon={<Clock3 size={19}/>} color="amber"/><Metric label="Respostas" value={`${totals.total?Math.round(totals.answered/totals.total*100):0}%`} icon={<BarChart3 size={19}/>} color="purple"/></div>}
        {data.classes.length?<div className="class-grid">{data.classes.map(c=>{const st=stats(data,c,data.surveys.find(s=>s.class_id===c.id&&s.code==='F4'));const ready=!!c.followup_on&&brazilToday()>=c.followup_on;const pendingReview=classStudents(data,c.id).filter(s=>!s.enrollment.excluded&&s.enrollment.review_pending).length;return <button className="class-card" key={c.id} onClick={()=>{setClassId(c.id);setPage('classes');}}><div className="class-top"><span className="class-code">{c.code}</span><ChevronRight size={20}/></div><h3>{c.name}</h3><p className="muted">{date(c.starts_on)} – {date(c.ends_on)}{c.shift?` · ${c.shift}`:''}</p><div className="class-numbers"><strong>{st.percent}<span>%</span></strong><span>{st.answered}/{st.total} respostas</span></div><div className="progress"><span style={{width:`${st.percent}%`}}/></div><div className="class-bottom"><span>{st.pending} pendentes</span><span>Form 4 · {date(c.followup_on)}</span></div><div className="class-footer"><span>{ready?'Aplicação liberada':'Aguardar 3 semanas'}</span><span>{pendingReview?`${pendingReview} em conferência`:''}</span></div></button>;})}</div>:<Empty>{admin?'Importe o quadro de gestão.':'Nenhuma turma liberada.'}</Empty>}</>}
      {page==='classes'&&classroom&&<><button className="back-link" onClick={()=>setClassId(null)}><ArrowLeft size={16}/>Turmas</button><div className="page-heading"><div><h1>{classroom.code} · {classroom.name}</h1><p>{date(classroom.starts_on)} – {date(classroom.ends_on)} <span className="date-divider">/</span> Form 4 · {date(classroom.followup_on)}</p></div>{admin&&<button className="button primary" onClick={()=>setWorkflow('attendance')}><FileText size={17}/>Lista de presença</button>}</div><StudentList data={data} classroom={classroom} survey={survey} admin={!!admin} onEdit={setEditing}/></>}
      {page==='imports'&&admin&&<><div className="page-heading"><h1>Dados</h1></div><div className="workflow-grid">{([{kind:'management',label:'Quadro de gestão',format:'CSV',icon:FileSpreadsheet},{kind:'attendance',label:'Lista de presença',format:'PDF por turma',icon:FileText},{kind:'form4',label:'Respostas · Form 4',format:'CSV / XLSX',icon:CheckCircle2}] as const).map((w,i)=><button className="workflow-card" key={w.kind} disabled={w.kind!=='management'&&!data.classes.length} onClick={()=>setWorkflow(w.kind)}><span className="workflow-step">0{i+1}</span><w.icon size={25}/><h2>{w.label}</h2><span>{w.format}</span><Upload size={16}/></button>)}</div>{data.sources.length>0&&<section className="student-panel source-history"><div className="table-scroll"><table><thead><tr><th>Últimos uploads</th><th>Linhas</th><th>Data</th></tr></thead><tbody>{[...data.sources].sort((a,b)=>b.imported_at.localeCompare(a.imported_at)).slice(0,8).map(s=><tr key={s.id}><td>{s.filename}</td><td>{s.row_count}</td><td>{date(s.imported_at)}</td></tr>)}</tbody></table></div></section>}</>}
      {page==='review'&&admin&&<Review data={data} busy={busy} onResolve={async(id,studentId,targetClass,state,reason)=>mutate(()=>rpc('resolve_form4',{p_id:id,p_student_id:studentId,p_class_id:targetClass,p_state:state,p_reason:reason}),'Conferência salva.')} onReconcile={async()=>{const raw=data.submissions.map(s=>s.answers);const prepared=reconcileForm4(data);await mutate(()=>rpc('import_form4',{p_rows:prepared,p_source:raw,p_filename:'Conciliação'}),'Conciliação atualizada.');}}/>}
      {page==='messages'&&admin&&<MessageSettings data={data} busy={busy} onSave={s=>mutate(()=>saveSurvey(s),'Mensagem salva.')}/>}
      {page==='analysis'&&admin&&<AIAnalysis data={data} onReview={(submissionId,studentId,targetClass)=>setAIReview({submissionId,studentId,classId:targetClass})}/>}
      {page==='access'&&admin&&<AccessSettings data={data} busy={busy} onChange={(email,cid,granted)=>mutate(()=>rpc('set_class_access',{p_email:email,p_class_id:cid,p_granted:granted}),granted?'Acesso liberado.':'Acesso removido.')}/>}
      <footer>British Council · SIDP · Fase V<span>MERL · ARCA</span></footer>
    </div></main>{toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
    {workflow&&admin&&<ImportWorkflows kind={workflow} data={data} classId={classId||undefined} onClose={()=>setWorkflow(null)} onSave={saveImport}/>}
    {editing&&classroom&&admin&&<StudentDialog student={editing} classroom={classroom} data={data} onClose={()=>setEditing(null)} onSave={async(urn,name,phone,targetClass,excluded,reason)=>{await mutate(()=>rpc('save_participant',{p_student_id:editing.id,p_class_id:classroom.id,p_to_class:targetClass,p_urn:urn,p_name:name,p_phone:phone,p_excluded:excluded,p_reason:reason}),'Participante atualizado.');setEditing(null);}}/>}
    {aiReview&&admin&&data.submissions.some(s=>s.id===aiReview.submissionId)&&<ResolveDialog data={data} submission={data.submissions.find(s=>s.id===aiReview.submissionId)!} initialSelection={`${aiReview.classId}|${aiReview.studentId}`} onClose={()=>setAIReview(null)} onResolve={async(studentId,targetClass,state,reason)=>{await mutate(()=>rpc('resolve_form4',{p_id:aiReview.submissionId,p_student_id:studentId,p_class_id:targetClass,p_state:state,p_reason:reason}),'Conferência salva.');setAIReview(null);}}/>}
  </div>;
}
function Login({error}:{error:string}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');return <div className="login-minimal"><div className="login-form"><Brand/><h1>Form 4</h1>{(error||localError)&&<div className="alert error" role="alert">{localError||error}</div>}<form onSubmit={async e=>{e.preventDefault();if(!supabase)return;setBusy(true);setLocalError('');try{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}catch(e){setLocalError(errorText(e));}finally{setBusy(false);}}}><label>E-mail<input required type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary full" disabled={busy||!supabase}>{busy?'Entrando…':'Entrar'}</button></form>{!supabase&&<p className="connection-note">Configure a conexão Supabase conforme o README.</p>}<small>SIDP · British Council · Fase V</small></div></div>;}
function StudentList({data,classroom,survey,admin,onEdit}:{data:Dataset;classroom:ClassRow;survey?:Survey;admin:boolean;onEdit:(s:Student)=>void}){
  const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(50);useEffect(()=>{setLimit(50);},[classroom.id,query,filter]);
  const all=classStudents(data,classroom.id).filter(s=>s.enrollment.attendance_verified!==false);const st=stats(data,classroom,survey);const flags=(s:typeof all[number])=>Array.from(new Set([...(s.enrollment.attention||[]),...(survey?responseFor(data,survey.id,s.id)?.attention||[]:[]),...(s.enrollment.review_pending?['Resposta em conferência']:[])]));
  const visible=all.filter(s=>{const answered=survey&&responseFor(data,survey.id,s.id);const selected=filter==='excluded'?s.enrollment.excluded:!s.enrollment.excluded&&(filter==='all'||filter==='pending'&&!answered||filter==='answered'&&!!answered||filter==='attention'&&!!flags(s).length);return selected&&`${admin?s.name:''} ${s.urn} ${s.phone}`.toLowerCase().includes(query.toLowerCase());});const ready=!!classroom.followup_on&&brazilToday()>=classroom.followup_on;
  return <><div className="metrics compact"><Metric label="Participantes" value={st.total} icon={<Users size={18}/>}/><Metric label="Responderam" value={st.answered} icon={<CheckCircle2 size={18}/>} color="green"/><Metric label="Pendentes" value={st.pending} icon={<Clock3 size={18}/>} color="amber"/></div><section className="student-panel"><div className="list-toolbar"><div className="tabs">{[['all','Todos'],['pending','Pendentes'],['answered','Responderam'],['attention','Atenção'],...(admin?[['excluded','Excluídos']]:[])].map(([id,label])=><button key={id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Buscar participante" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar"/></label></div>{visible.length?<><div className="table-scroll"><table><thead><tr>{admin&&<th>Participante</th>}<th>URN</th><th>Form 4</th><th>Contato</th><th><span className="sr-only">Editar</span></th></tr></thead><tbody>{visible.slice(0,limit).map(s=>{const response=survey&&responseFor(data,survey.id,s.id);const attention=flags(s);const url=ready&&survey&&!response&&!s.enrollment.excluded&&!s.enrollment.review_pending&&!s.urn.startsWith('SEM-')?whatsappUrl(s,classroom,survey,!admin):null;return <tr key={s.id}><>{admin&&<td><div className="person"><span className="avatar">{initials(s.name)}</span><strong>{s.name}</strong></div></td>}<td><span className="urn">{urnLabel(s.urn)}</span>{attention.length>0&&<span className="attention-icon" title={attention.join('; ')} aria-label={attention.join('; ')}><AlertCircle size={15}/></span>}</td></><td>{s.enrollment.excluded?<span className="status neutral">Excluído</span>:response?<span className="status answered"><Check size={13}/>Respondeu</span>:<span className="status pending">{s.enrollment.review_pending?'Em conferência':'Pendente'}</span>}</td><td>{url?<a className="whatsapp-button" href={url} target="_blank" rel="noopener noreferrer" aria-label={`WhatsApp para ${admin?s.name:s.urn}`}><MessageSquare size={15}/>WhatsApp<ExternalLink size={12}/></a>:<span className="muted small">{response?date(response.responded_at):!ready?`Aguardar ${date(classroom.followup_on)}`:s.enrollment.review_pending?'Conferir resposta':!s.phone?'Sem telefone':s.urn.startsWith('SEM-')?'Sem matrícula':'Link / telefone'}</span>}</td><td>{admin&&<button className="icon-button" aria-label={`Editar ${s.name}`} onClick={()=>onEdit(s)}><MoreHorizontal size={18}/></button>}</td></tr>;})}</tbody></table></div><div className="table-bottom"><span>{Math.min(limit,visible.length)}/{visible.length}</span>{limit<visible.length&&<button className="button secondary" onClick={()=>setLimit(l=>l+50)}>Mais</button>}</div></>:<Empty>{all.length?'Nenhum resultado.':'Importe a lista de presença.'}</Empty>}</section></>;
}
function Review({data,busy,onResolve,onReconcile}:{data:Dataset;busy:boolean;onResolve:(id:string,student:string|null,classId:string|null,state:string,reason:string)=>Promise<void>;onReconcile:()=>Promise<void>}){
  const [filter,setFilter]=useState('review'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Form4Submission|null>(null),[error,setError]=useState(''),[limit,setLimit]=useState(50);const visible=data.submissions.filter(s=>(filter==='review'?s.state==='review':filter==='flags'?s.state==='linked'&&s.flags.length>0:s.state==='ignored')&&`${s.source_name} ${s.source_urn}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-heading"><h1>Conferência</h1><button className="button secondary" disabled={busy||!data.submissions.length} onClick={async()=>{setError('');try{await onReconcile();}catch(e){setError(errorText(e));}}}><RefreshCw size={16}/>Conciliar novamente</button></div>{error&&<div className="alert error" role="alert">{error}</div>}<section className="student-panel"><div className="list-toolbar"><div className="tabs">{[['review','A revisar'],['flags','Sinalizadas'],['ignored','Ignoradas']].map(([id,label])=><button key={id} className={filter===id?'selected':''} onClick={()=>{setFilter(id);setLimit(50);}}>{label}</button>)}</div><label className="search"><Search size={16}/><input aria-label="Buscar resposta" placeholder="Buscar" value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}}/></label></div>{visible.length?<><div className="table-scroll"><table><thead><tr><th>Nome no Form 4</th><th>Matrícula</th><th>Atenção</th><th><span className="sr-only">Revisar</span></th></tr></thead><tbody>{visible.slice(0,limit).map(s=><tr key={s.id}><td><strong>{s.source_name||'—'}</strong><small className="cell-meta">{date(s.submitted_at)}</small></td><td><span className="urn">{s.source_urn||'—'}</span></td><td><span className="flag-text">{s.flags.join(' · ')||s.review_reason||'—'}</span></td><td><button className="button secondary" onClick={()=>setSelected(s)}>Conferir</button></td></tr>)}</tbody></table></div>{limit<visible.length&&<div className="table-bottom"><button className="button secondary" onClick={()=>setLimit(n=>n+50)}>Mais</button></div>}</>:<Empty>Nenhuma resposta neste filtro.</Empty>}</section>{selected&&<ResolveDialog data={data} submission={selected} onClose={()=>setSelected(null)} onResolve={async(s,c,state,reason)=>{await onResolve(selected.id,s,c,state,reason);setSelected(null);}}/>}</>;
}
function ResolveDialog({data,submission,onClose,onResolve,initialSelection}:{data:Dataset;submission:Form4Submission;initialSelection?:string;onClose:()=>void;onResolve:(student:string|null,classId:string|null,state:string,reason:string)=>Promise<void>}){
  const first=submission.candidates[0];const [selection,setSelection]=useState(initialSelection||(submission.student_id?`${submission.class_id}|${submission.student_id}`:first?`${first.class_id}|${first.student_id}`:'')),[reason,setReason]=useState(submission.review_reason||'Correspondência conferida'),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(state:string){setBusy(true);setError('');try{const [classId,student]=selection.split('|');await onResolve(state==='linked'?student:null,state==='linked'?classId:null,state,reason);}catch(e){setError(errorText(e));}finally{setBusy(false);}}const options=data.classes.flatMap(c=>classStudents(data,c.id).filter(s=>!s.enrollment.excluded&&s.enrollment.attendance_verified).map(s=>({key:`${c.id}|${s.id}`,label:`${c.code} · ${s.name} · ${urnLabel(s.urn)}`})));
  return <Dialog title="Conferir resposta" onClose={()=>{if(!busy)onClose();}} wide>{error&&<div className="alert error" role="alert">{error}</div>}<div className="response-identity"><h3>{submission.source_name||'Sem nome'}</h3><p>{submission.source_urn||'Sem matrícula'} · {date(submission.submitted_at)}</p>{submission.flags.length>0&&<div className="flag-list">{submission.flags.map(f=><span className="status pending" key={f}>{f}</span>)}</div>}</div>{submission.candidates.length>0&&<div className="candidate-list">{submission.candidates.map(c=>{const student=data.students.find(s=>s.id===c.student_id);return <button key={c.class_id+c.student_id} className={selection===`${c.class_id}|${c.student_id}`?'candidate selected':'candidate'} onClick={()=>setSelection(`${c.class_id}|${c.student_id}`)}><div><strong>{student?.name}</strong><small>{data.classes.find(x=>x.id===c.class_id)?.code} · {student?urnLabel(student.urn):'—'} · {c.reason}</small></div><span>{Math.round(c.score*100)}%</span></button>;})}</div>}<label>Participante<select value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Selecionar</option>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label><label>Registro da conferência<input required value={reason} onChange={e=>setReason(e.target.value)}/></label><details className="raw-details"><summary>Respostas do formulário</summary><dl className="raw-answers">{Object.entries(submission.answers).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v??'—')}</dd></div>)}</dl></details><div className="dialog-actions"><button className="button secondary" disabled={busy||!reason.trim()} onClick={()=>void save('ignored')}>Ignorar registro</button><button className="button primary" disabled={busy||!selection||!reason.trim()||!submission.submitted_at} onClick={()=>void save('linked')}>Confirmar vínculo<Check size={16}/></button></div>{!submission.submitted_at&&<p className="muted small">Corrija a data no arquivo e importe novamente.</p>}</Dialog>;
}
function MessageSettings({data,busy,onSave}:{data:Dataset;busy:boolean;onSave:(s:Survey)=>Promise<void>}){const surveys=data.surveys.filter(s=>s.code==='F4'&&data.classes.some(c=>c.id===s.class_id));const [id,setId]=useState(surveys[0]?.id||''),[draft,setDraft]=useState<Survey|undefined>(surveys[0]),[error,setError]=useState('');const current=surveys.find(s=>s.id===id);useEffect(()=>setDraft(current),[current,id]);const classroom=data.classes.find(c=>c.id===draft?.class_id);
  return <><div className="page-heading"><h1>Mensagens</h1></div>{!draft||!classroom?<Empty>Importe o quadro de gestão.</Empty>:<><label className="survey-selector">Turma<select value={id} onChange={e=>setId(e.target.value)}>{surveys.map(s=><option key={s.id} value={s.id}>{data.classes.find(c=>c.id===s.class_id)?.code}</option>)}</select></label><div className="message-layout"><form className="panel" onSubmit={async e=>{e.preventDefault();setError('');if(draft.url&&!validSurveyUrl(draft.url)){setError('Use um link HTTPS.');return;}try{await onSave(draft);}catch(e){setError(errorText(e));}}}>{error&&<div className="alert error" role="alert">{error}</div>}<label>Link · Form 4<input type="url" value={draft.url} onChange={e=>setDraft({...draft,url:e.target.value})} placeholder="https://..."/></label><label>Mensagem<textarea rows={10} required value={draft.message_template} onChange={e=>setDraft({...draft,message_template:e.target.value})}/></label><div className="variable-chips">{['nome','nome_completo','turma','link','matricula'].map(v=><button type="button" key={v} onClick={()=>setDraft({...draft,message_template:draft.message_template+` {${v}}`})}>{`{${v}}`}</button>)}</div><button className="button primary" disabled={busy}>Salvar<Check size={16}/></button></form><div className="message-preview"><div className="preview-header"><MessageSquare size={18}/><strong>Mensagem</strong><span>{date(classroom.followup_on)}</span></div><div className="message-bubble">{renderMessage(draft.message_template,{id:'',name:'Maria',urn:'L-B10001',phone:''},classroom,draft)}</div></div></div></>}</>;
}
function AccessSettings({data,busy,onChange}:{data:Dataset;busy:boolean;onChange:(email:string,classId:string,granted:boolean)=>Promise<void>}){const [email,setEmail]=useState(''),[id,setId]=useState(data.classes[0]?.id||''),[error,setError]=useState('');return <><div className="page-heading"><h1>Acessos</h1></div>{error&&<div className="alert error" role="alert">{error}</div>}<form className="panel access-form" onSubmit={async e=>{e.preventDefault();setError('');try{await onChange(email,id,true);setEmail('');}catch(e){setError(errorText(e));}}}><label>E-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Turma<select value={id} onChange={e=>setId(e.target.value)}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label><button className="button primary" disabled={busy||!id}>Liberar</button></form><section className="student-panel access-table">{data.assignments.length?<div className="table-scroll"><table><thead><tr><th>Conta</th><th>Turma</th><th><span className="sr-only">Remover</span></th></tr></thead><tbody>{data.assignments.filter(a=>data.classes.some(c=>c.id===a.class_id)).map(a=>{const p=data.profiles.find(p=>p.id===a.user_id);return <tr key={a.user_id+a.class_id}><td>{p?.email}</td><td>{data.classes.find(c=>c.id===a.class_id)?.code}</td><td><button className="text-button danger" disabled={busy||!p} onClick={async()=>{setError('');try{await onChange(p!.email,a.class_id,false);}catch(e){setError(errorText(e));}}}>Remover</button></td></tr>;})}</tbody></table></div>:<Empty>Nenhum acesso liberado.</Empty>}</section></>;}
function StudentDialog({student,classroom,data,onClose,onSave}:{student:Student;classroom:ClassRow;data:Dataset;onClose:()=>void;onSave:(urn:string,name:string,phone:string,toClass:string,excluded:boolean,reason:string)=>Promise<void>}){const e=data.enrollments.find(e=>e.student_id===student.id&&e.class_id===classroom.id)!;const [urn,setUrn]=useState(student.urn.startsWith('SEM-')?'':student.urn),[name,setName]=useState(student.name),[phone,setPhone]=useState(student.phone),[id,setId]=useState(classroom.id),[excluded,setExcluded]=useState(e.excluded),[reason,setReason]=useState(e.exclusion_reason),[busy,setBusy]=useState(false),[error,setError]=useState('');const response=data.responses.find(r=>r.student_id===student.id&&r.class_id===classroom.id);const answers=data.answers.find(a=>a.response_id===response?.id)?.answers;
  return <Dialog title="Participante" onClose={()=>{if(!busy)onClose();}}>{error&&<div className="alert error" role="alert">{error}</div>}<form onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await onSave(urn,name,phone,id,excluded,reason);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Matrícula<input value={urn} onChange={e=>setUrn(e.target.value)} pattern="\S+"/></label><label>Telefone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Turma<select value={id} onChange={e=>setId(e.target.value)}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.code}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={excluded} onChange={e=>setExcluded(e.target.checked)}/><span>Excluir do acompanhamento</span></label>{excluded&&<label>Motivo<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>}{answers&&<details className="raw-details"><summary>Form 4 · {date(response?.responded_at)}</summary><dl className="raw-answers">{Object.entries(answers).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v??'—')}</dd></div>)}</dl></details>}<div className="dialog-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancelar</button><button className="button primary" disabled={busy}>Salvar<Check size={16}/></button></div></form></Dialog>;
}
